### ISSUE TITLE
depgen error

### ISSUE THREAD

**Issue by skunk73** [nichoski/kergen#6]
linux-4.1.26-gentoo
python-3.4.3

```
funk linux # depgen CONFIG_MEGARAID_SAS CONFIG_EDAC_I7CORE CONFIG_DRM_MGAG200 CONFIG_USB CONFIG_BLK_DEV_SD EXT4_FS PROC_FS CONFIG_BNX2 CONFIG_USB_HID CONFIG_USB_EHCI_PCI CONFIG_BLK_DEV_SR CONFIG_ATA_GENERIC CONFIG_ATA_PIIX CONFIG_LPC_ICH CONFIG_HOTPLUG_PCI_SHPC CONFIG_USB_UHCI_HCD
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/depgen", line 384, in <module>
    deps = Depgen(kconf_info_list, config, options_list)
  File "/usr/lib/python-exec/python3.4/depgen", line 121, in __init__
    self.check_for_deps_of_deps()
  File "/usr/lib/python-exec/python3.4/depgen", line 306, in check_for_deps_of_deps
    temp = Depgen(self.kconf_info_list, config, line)
  File "/usr/lib/python-exec/python3.4/depgen", line 121, in __init__
    self.check_for_deps_of_deps()
  File "/usr/lib/python-exec/python3.4/depgen", line 306, in check_for_deps_of_deps
    temp = Depgen(self.kconf_info_list, config, line)
  File "/usr/lib/python-exec/python3.4/depgen", line 122, in __init__
    self.validate_possible_lists_against_itself()
  File "/usr/lib/python-exec/python3.4/depgen", line 366, in validate_possible_lists_against_itself
    self.remove_lines_containing(dependency[1:])
  File "/usr/lib/python-exec/python3.4/depgen", line 343, in remove_lines_containing
    option.remove(line)
AttributeError: 'PossibleLists' object has no attribute 'remove'
```

**Comment by nichoski** [comment]
Fixed.
Depgen was trying to remove a line in the PossibleLists object instead of its list of lines.
Thank you for reporting.

**Comment by skunk73** [comment]
it works now, thank you!
